//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarCodeInvoice.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SellMaster
    {
        public string Id { get; set; }
        public string CompanyId { get; set; }
        public string BranchId { get; set; }
        public string BusinessIdentificationNumberId { get; set; }
        public string FiscalPeriodId { get; set; }
        public string FiscalYearId { get; set; }
        public string PartyId { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceNoOld { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.TimeSpan IssueTime { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.TimeSpan DeliveryTime { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string RouteCode { get; set; }
        public string TermCode { get; set; }
        public string ManifestNumber { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Place { get; set; }
        public string VehicleId { get; set; }
        public string Car { get; set; }
        public Nullable<int> ChallanType { get; set; }
        public string ChallanTypeName { get; set; }
        public decimal TotalWithoutVAT { get; set; }
        public decimal TotalVAT { get; set; }
        public decimal TotalWithVAT { get; set; }
        public decimal TotalWithoutSD { get; set; }
        public decimal TotalSD { get; set; }
        public decimal Discount { get; set; }
        public decimal Adjustment { get; set; }
        public decimal NetAmount { get; set; }
        public Nullable<decimal> SumActualValue { get; set; }
        public Nullable<decimal> SumAmountCustomerPrice { get; set; }
        public string Remarks { get; set; }
        public bool ExportChallan { get; set; }
        public bool PrintStatus { get; set; }
        public bool Accept { get; set; }
        public bool Active { get; set; }
        public bool Archive { get; set; }
        public bool IsVDS { get; set; }
        public Nullable<decimal> VDSAmount { get; set; }
        public string VatOneNo { get; set; }
        public string SalesType { get; set; }
        public string PartyVATRegNO { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedFromIP { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedFromIP { get; set; }
        public string InvoicePeriodId { get; set; }
        public string SellContractId { get; set; }
        public Nullable<bool> IsRecurring { get; set; }
        public string CPC { get; set; }
        public string OfficeCode { get; set; }
        public Nullable<decimal> TotalHDSC { get; set; }
        public string PartyCode { get; set; }
        public string PartyName { get; set; }
        public string SignatoryId { get; set; }
        public Nullable<decimal> TotalTradeValue { get; set; }
        public Nullable<decimal> TotalTradeVAT { get; set; }
        public decimal ExportRate { get; set; }
        public string PartyAddress { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> ReceivedAmount { get; set; }
        public Nullable<decimal> ChangeAmount { get; set; }
        public string PartyBranchId { get; set; }


        [NotMapped]
        public string Barcode { get; set; }
    }
}
